name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'  

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests (if any)
        run: |
          cd frontend
          npm test -- --watch=false

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  backend:
    runs-on: ubuntu-latest
    needs: frontend 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests (if any)
        run: |
          cd backend
          pytest  

      - name: Deploy backend (Example)
        run: |
          cd backend
         

  
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      
